### ISSUE TITLE
How to create & map a convex hull from a set of points?

### ISSUE THREAD

**Issue by rossmounce** [ropensci/mapr#23]
I hope this isn't too lazy of me?

My use case is simple to describe: 
1. I'd like to make a simple convex hull of occurrences for a species. (simple)
2. From that convex hull I'd like to compute how many countries the convex hull covers (less simple)

In conservation biology a convex hull seems also to be known as the extent of occurrence (EOO) of a species (e.g. figure 1a here: http://www.int-res.com/articles/esr2008/6/n006p127.pdf ). This would be a popular use-case for `mapr` & occurrence data I think.

Q2 is slightly subtler. The convex hull could be composed from say four occurrence records, each in a different country, but the simple convex hull could conceivably cover _more_ than four different countries. I want to know ALL the different countries that are at least partially covered by the convex hull between the pts, not just the country of origin of the points/occurrences. Identity of the countries overlapped by the EOO is key too, not just a numerical count of how many.

**Comment by sckott** [comment]
thanks for the use case, thinking

**Comment by sckott** [comment]
Here's my thoughts - excuse me if i'm telling you anything you already know 

## convex hull's

There are tools in base R (see the `chull()` function) and in e.g., `vegan`, eg.., could do in base R

``` r
X <- matrix(stats::rnorm(2000), ncol = 2)
plot(X, cex = 0.5)
hpts <- chull(X)
hpts <- c(hpts, hpts[1])
lines(X[hpts, ])
```

![img](http://f.cl.ly/items/1o1q3l1u2J1V410m1H0L/Screen%20Shot%202016-06-02%20at%201.44.14%20PM.png)

or with `vegan` package

``` r
library(vegan)
data(dune)
data(dune.env)
mod <- cca(dune ~ Management, dune.env)
plot(mod, type="n", scaling = 3)
ordihull(mod, dune.env$Management, scaling = 3, label = TRUE)
```

![img2](http://cl.ly/gLd3/Screen%20Shot%202016-06-02%20at%201.46.47%20PM.png)

Though using `vegan` you have to create an ordination first, which is less intuitive. 

An eg with real occurrence data

``` r
library("rgbif")
res <- occ_search(scientificName = "Puma concolor", limit = 100)
hpts <- chull(na.omit(res$data[,c('decimalLongitude','decimalLatitude')]))
hpts <- c(hpts, hpts[1])
plot(na.omit(res$data[,c('decimalLongitude','decimalLatitude')]), cex = 0.5)
lines(na.omit(res$data[,c('decimalLongitude','decimalLatitude')])[hpts, ])
```

![img3](http://cl.ly/gLaN/Screen%20Shot%202016-06-02%20at%202.05.57%20PM.png)

## countries covered by convex hulls

Interesting problem. Here's one way to do it:

``` r
library("rgbif")
library("sp")
library("rgeos")
library("rworldmap")
res <- occ_search(scientificName = "Puma concolor", limit = 100)
coords <- na.omit(res$data[,c('decimalLongitude','decimalLatitude')])
coordinates(coords) <- ~decimalLongitude + decimalLatitude
hull <- gConvexHull(coords)
proj4string(hull) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
countriesLow <- spTransform(countriesLow, CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))
df <- over(hull, countriesLow, returnList = TRUE)[[1]]
as.character(df$NAME)
#>  [1] "Argentina"     "Belize"        "Bolivia"       "Brazil"        "Canada"        "Chile"         "Colombia"      "Costa Rica"    "Cuba"         
#> [10] "Cayman Is."    "Ecuador"       "Guatemala"     "Honduras"      "Jamaica"       "Mexico"        "Nicaragua"     "Panama"        "Peru"         
#> [19] "Paraguay"      "El Salvador"   "United States" "Venezuela"
```

## visualizing convex hulls

Would be cool to facilitate visualizing these with mapr - though not sure how easy it will be across the different interfaces we support in this pkg (ggplot2 vs. base plots, vs. interactive leaflet maps). Can try at least...

**Comment by rossmounce** [comment]
ah... I should have known R would already have convex hull implemented! But now I know of `chull` that has helped me DuckDuckGo some specific pointers for visualization e.g. this example of mapping a convex hull around points on a Leaflet-based world map: https://rstudio.github.io/leaflet/showhide.html 

Not quite sure how static academic journal figures are going to handle a Leaflet map... (high-res screenshot? :cry: )

Your solution to countries covered by convex hulls is super useful: i'll definitely be using that, thanks again!

**Comment by sckott** [comment]
Great, glad the examples were helpful. And thanks for the leaflet example, will use that to see about implementing here. 

> Not quite sure how static academic journal figures are going to handle a Leaflet map

if only!

**Comment by sckott** [comment]
@rossmounce can reinstall `devtools::install_github("ropensci/mapr")` and try some of the examples that include hulls, e.g.

``` r
library("mapr")
library("spocc")
library("magrittr")
spp <- c('Danaus plexippus', 'Accipiter striatus', 'Pinus contorta')
dat <- occ(spp, from = 'gbif', limit = 30, has_coords = TRUE)
map_leaflet(dat)
map_leaflet(dat) %>% hull()
```

``` r
library("mapr")
library("rgbif")
res <- occ_search(scientificName = "Puma concolor", limit = 100)
map_plot(res, hull = FALSE)
map_plot(res, hull = TRUE)
```

**Comment by rossmounce** [comment]
I meant to give this feedback a few days earlier but I got distracted...

I couldn't seem to get your examples to work unfortunately e.g.

```
devtools::install_github("ropensci/mapr", force=TRUE)
Downloading GitHub repo ropensci/mapr@master
from URL https://api.github.com/repos/ropensci/mapr/zipball/master
Installing mapr
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpEe4Gh8/devtools66f75291ad74/ropensci-mapr-e2a6100'  \
  --library='/home/ross/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘mapr’ ...
** R
** inst
** tests
** preparing package for lazy loading
Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘DBI’: not turning on duplicate class definitions for this class.
Note: the specification for S3 class “difftime” in package ‘lubridate’ seems equivalent to one from package ‘DBI’: not turning on duplicate class definitions for this class.
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘DBI’: not turning on duplicate class definitions for this class.
Note: the specification for S3 class “difftime” in package ‘lubridate’ seems equivalent to one from package ‘DBI’: not turning on duplicate class definitions for this class.
* DONE (mapr)
Reloading installed mapr
library("mapr")
library("spocc")
library("magrittr")
library("rgbif")
res <- occ_search(scientificName = "Puma concolor", limit = 100)
map_plot(res, hull = FALSE)
Warning message:
In plot.xy(xy.coords(x, y), type = type, ...) :
  "hull" is not a graphical parameter
map_plot(res, hull = TRUE)
Warning message:
In plot.xy(xy.coords(x, y), type = type, ...) :
  "hull" is not a graphical parameter
```

**Comment by sckott** [comment]
bummer, thanks, will look at this

**Comment by sckott** [comment]
@rossmounce

Sorry about that! Changes are on the branch `hull`, try 

`devtools::install_github("ropensci/mapr@dev")`

then try egs again

**Comment by rossmounce** [comment]
Got it! Looking good. thanks!

**Comment by sckott** [comment]
works with 3 of the 5 plotting methods now, will try to add the others later.
