### ISSUE TITLE
map idea: heat map of species per cell

### ISSUE THREAD

**Issue by sckott** [ropensci/mapr#31]
via https://discuss.ropensci.org/t/some-thoughts-on-working-with-rgbif-occurrence-data-including-mapping/1105/5 

duplicate something like what this pkg does

```r
library(monographaR)
data(monographaR_examples)
mapDiversity(monographaR_examples$map_data, resolution = 1, plot = TRUE, plot.with.grid = TRUE, legend = TRUE, export = FALSE)
```

<img width="706" alt="screen shot 2018-04-04 at 3 10 46 pm" src="https://user-images.githubusercontent.com/577668/38337508-690fd476-381a-11e8-8251-5a7a2e08746f.png">

**Comment by sckott** [comment]
and do for as many map tools as possible, esp. base/ggplot2/leaflet

**Comment by oolonek** [comment]
Up ! Any news on this type of plotting ? Or equivalent packages to do so ?

**Comment by sckott** [comment]
thanks for the ping @oolonek - i have not worked on this yet. will look into it soon
